### PR TITLE
Support CMake Only

### PR DESCRIPTION
**Pull request by Andres6936**
Since Conan has problems handling dependencies, the new goal is to support CMake without the help of Conan, i.e. the dependencies have to be provided by the user.

### CODE REVIEW

**Comment by Andres6936** [comment]
I want you to check the following: Execution of Target samples_cpp

```sh
mkdir build-unused
cd build-unused
cmake ..
cmake --build . --target samples_cpp
make
cd samples/showcase/
./samples_cpp
```

**Comment by HexDecimal** [comment]
It seems you've deleted `samples_cpp.cpp` when you meant to move it?

Also, you really need to get an [EditorConfig](https://editorconfig.org/) plugin for your text editor.

**Comment by Andres6936** [comment]
> It seems you've deleted samples_cpp.cpp when you meant to move it?

Generally CLion move the file `git move`, but I don't know what happened this time.

> Also, you really need to get an EditorConfig plugin for your text editor.

A good alternative (which supports CLion) is `.clang-format`, you don't have to worry, I'll format everything I need before the Merge.

**Comment by Andres6936** [comment]
samples_cpp.cpp is back again. You were right, I wanted to move it instead of eliminating it.

**Comment by Andres6936** [comment]
I don't know how well the news will suit you, but I've made too big a change for you to accept, I've changed the structure of the project entirely, now the headers reside in a new directory, the goal is to allow installation in a much cleaner way.

Again, I haven't done the Pull, although I want you to review it and maybe there is a possibility to integrate it into Libtcod.

Here the link: https://github.com/Andres6936/libtcod/tree/NewStruct

**Pull request closed without merging**
