### PR TITLE
Added advice on alternatives to deprecated console functions.

### PR DESCRIPTION
**Pull request by charlieb**

### CODE REVIEW

**Comment by HexDecimal** [comment]
An issue is that those attributes are also deprecated since they're still part of the console defaults, but it's harder to put deprecation tags on them.  The correct solution is to use the newer functions which bypass the defaults entirely whenever possible.

**Comment by charlieb** [comment]
I didn't know they were also deprecated. If you tell me the right way I'll make a new pull request. I couldn't figure out what the correct new way is.

**Comment by charlieb** [comment]
TCOD_console_set_color_control and friends is the new way?

**Comment by HexDecimal** [comment]
`TCOD_console_set_color_control` uses a thread-unsafe global state, so I wanted to remove that too.
It's just `TCOD_COLCTRL_FORE_RGB/TCOD_COLCTRL_BACK_RGB` when you want to change colors in the middle of printing.

I've neglected the C API, so the real function to use has been stuff like `TCOD_console_printn` and `TCOD_console_draw_rect_rgb`.  These functions ignore console defaults entirely, you give them the parameters which will be active instead.  I only did enough so that I could port these functions to the other languages.

For C++ the `tcod::print` and `tcod::draw_rect` functions are what you'd want to use.  These are generally complete, but maybe some of the parameters could be replaced by structs.

I'm not entirely sure what's documented, and it seems a lot of stuff I plan to deprecate hasn't been marked yet, such as the `TCOD_console_put_char` style functions and ones like `TCOD_console_hline`.  I should probably make a new issue to track these changes and what was planned for them.

**Comment by charlieb** [comment]
I will close this request and make another one advising the use of `TCOD_console_printn` and `TCOD_console_draw_rect_rgb`. Thanks.

**Pull request closed without merging**
