### PR TITLE
New printing api

### PR DESCRIPTION
**Pull request by hazeled**
A new PR with the correct branch. Adds "TCOD_printf_RGB", "TCOD_printn_RGB", and "TCOD_vprintf_RGB" (Along with a PrintParams struct) to console_printing.

### CODE REVIEW

**Comment by hazeled** [comment]
I'm busy right now, but when I get back at my home computer I'll fix the issues you posted about in #132

**Comment by hazeled** [comment]
Haha, in my defense - that DOES technically remove usage of "TCOD_console_print_internal". But that's on me for trying to push while distracted, fixed. I'm going to go ahead and get everything else done tonight, too

**Comment by HexDecimal** [comment]
The code wasn't formatted with clang-format, and and I fixed some issues which could've been found at compilation.  I've pushed these changes to your branch.

What tools are you using to code with?

**Comment by hazeled** [comment]
I use neovim and coc+clangd. What issues should I have caught at compile time? It compiled and ran perfectly when i tested it on my machine

**Comment by HexDecimal** [comment]
> What issues should I have caught at compile time? 

The new functions in headers ended with `_RGB` but those functions were called in the source as `_rgb`.

**Comment by hazeled** [comment]
> > What issues should I have caught at compile time?
> 
> The new functions in headers ended with `_RGB` but those functions were called in the source as `_rgb`.

Huh. My branch is (and was) reading as up-to-date, and it compiled with both of them being _rgb. They're also both still _rgb on my system. I think something might be wrong with my git install, I'm being careful about how I add/commit/push, and it seems like some things are either not being tracked or not being pushed. My apt has also been acting up lately, too, so I'm guessing I just need to fix my system

**Comment by HexDecimal** [comment]
I'd recommend getting the clang-format Vim plugin so that code formatting is automatic.

Depending on how you work with Git it can be easy to get confused over what's staged.  A command like `git commit -a` is less prone to accidentally leaving out unchanged files as long as there's no new ones.

**Comment by HexDecimal** [comment]
What remains are tests.  I'll probably finish this PR.

**Comment by hazeled** [comment]
Got it, I'll set it up. Also I'd be more than happy to finish up the tests if you haven't already

**Comment by HexDecimal** [comment]
I've already added tests.  Right now I'm just unsure if the params should be passed by value, when typically these structs are passed by pointer.

**Pull request merged**
